### ISSUE TITLE
Compile Error for STM32 Core for Arduino

### ISSUE THREAD

**Issue by momonator25** [xreef/EByte_LoRa_E22_Series_Library#1]
Hello I know this libary is not supposed to work with STM32 but it does with a little fix.
Right now there is a conflict in naming:
`statesNaming.h:20:13: error: 'SUCCESS' conflicts with a previous declaration 20 | SUCCESS = 1,
`
with
`stm32f1xx.h:166:3: note: previous declaration 'ErrorStatus SUCCESS' 166 | SUCCESS = 0U,
`

The compile error can be avoided if SUCCESS gets renamed.

**Comment by xreef** [comment]
Hi momonator25,
thanks for the alert, I'm going to fix as soon as possible (but I need some time).
Thanks again Renzo

**Comment by momonator25** [comment]
> 
> 
> Hi momonator25,
> thanks for the alert, I'm going to fix as soon as possible (but I need some time).
> Thanks again Renzo

No Problem and thanks for your fast reply! Don't hurry! Best regards

**Comment by xreef** [comment]
Hi momonator25,
I test e22 with STM32 ad arduino IDE and I haven't that problem, I had another problem with softwareserial and I'm going to fix It.
Witch platform do you use?
Bye Renzo

**Comment by lejibxl** [comment]
Dear xreef,
I encountered the same problem with a Nucleo-32 G031K8 card.
I renamed in file "statesNaming.h" "SUCCESS" term  to "SUCCESS_E22" and it works again
Thanx for your excellent  library!
