### ISSUE TITLE
How many device can send data a center Simultaneously?

### ISSUE THREAD

**Issue by fixajteknik** [xreef/EByte_LoRa_E22_Series_Library#10]
When I look at the information sheet of the e22 modules, it says that the buffer length is 1000 bytes and the subpackages of the Lora module can be reduced to 32 bytes. This is how I understand it 1 lora center can receive data from 1000/32 = 31 devices simultaneously. Please correct me if I'm wrong. 

![image](https://user-images.githubusercontent.com/73440569/152696368-d5bc687b-cf8d-4b17-bf85-1d6212d44c1d.png)

So, how can I retrieve data from these 30-odd points at the same time without losing data? I saw the following code `"e32ttl.receiveMessageUntil();"` on your [website ](https://www.mischianti.org/2019/10/21/lora-e32-device-for-arduino-esp32-or-esp8266-library-part-2/)but I couldn't see the usage example. Can you make an example? In addition, what is the reading speed of Lora modules, that is, how long should the waiting time be between messages from 30 points, ideally.

**Comment by xreef** [comment]
Hi @fixajteknik,
Your numbers are correct, the E22 has a buffer that can contain 1000byte if you don't read the data.
You can find some information about receive message until in this topic post https://www.mischianti.org/forums/topic/e32-900t20d-communication/#post-14357 .

But you can get the same result with structure, you can read partial structure to understand message type and then read the other. readMessageUntil It's only for string or similar. You can get some other information in this topic post https://www.mischianti.org/forums/topic/data-structure-lost/ .

Bye Renzo
