### ISSUE TITLE
configuration.TRANSMISSION_MODE.WORTransceiverControl = WOR_RECEIVER;

### ISSUE THREAD

**Issue by fixajteknik** [xreef/EByte_LoRa_E22_Series_Library#11]
`configuration.TRANSMISSION_MODE.WORTransceiverControl = WOR_RECEIVER;`

this commend not effect lora module parameters setting for E22 only transmitter works

actualy it work reverse, if I set receiver it goes transmitter mode and if I set transmitter it goes receiver mode

  //configuration.TRANSMISSION_MODE.WORTransceiverControl = WOR_TRANSMITTER;
  configuration.TRANSMISSION_MODE.WORTransceiverControl = WOR_RECEIVER;

**Comment by xreef** [comment]
Hi @fixajteknik,
It's very strange, the datasheet says that 1 is for the transmitter and 0 for the receiver.
I will try to test It as soon as possible.
Bye Renzo

**Comment by fixajteknik** [comment]
also there is no `c.close();` at any set configration exampls. did you forget or `c.close` unneccesary

**Comment by xreef** [comment]
Azz... no close is mandatory.
Thanks

**Comment by xreef** [comment]
Hi @fixajteknik,
I try to redo some tests and seems It's working correctly without inverting the configuration.
Can you retry, please?
Bye Renzo

**Comment by fixajteknik** [comment]
yes double check still reverse working.

also there is a new bug,

`  configuration.NETID = Netid;` is not save bigger number, it needs highbyte and lowbyte. also tested.

**Comment by xreef** [comment]
Hi fixajteknik,
ok, I'm going to retest the TRANSMISSION_MODE.

NetId can be only one byte in the register (like ADDH and ADDL) It can't be more than that.

Thanks, Renzo

**Comment by fixajteknik** [comment]
I have attached screenshoot, may be ı am making something wrong. on the other hand i didnt face any problem while working error translete or receiver.

![1](https://user-images.githubusercontent.com/73440569/212610060-4dff33f9-f24a-4969-a7ef-1b07864263e6.jpg)

![2](https://user-images.githubusercontent.com/73440569/212610105-680d00bf-dba7-448b-8231-e4857583ce2e.jpg)

**Comment by xreef** [comment]
Hi,
mmm... I think that I remember that when I do the test I find that the bug is in the EByte software.

But your test says that It's the correct mine value of EByte software value.

Bye Renzo

**Comment by xreef** [comment]
Hi @fixajteknik,
finally I receive the updated version from EByte

https://www.mischianti.org/forums/topic/fixed-ebyte-e22-desktop-program-for-usb-adapter/

Thanks Renzo
