### ISSUE TITLE
Wrong interpretation of returned string on WRITE_CFG_PWR_DWN_LOSE

### ISSUE THREAD

**Issue by MatteoGalet** [xreef/EByte_LoRa_E22_Series_Library#12]
When saving configuration on E22 UART module, C2 is the command that saves settings only temporary (not on persistent memory).
Unfortunately, code does not understand that the response command is still  C1 as per eByte datasheet, but expects it to be the same as the command sent (C2).

Configuration saves fine anyways.

https://github.com/xreef/EByte_LoRa_E22_Series_Library/blob/510e04e617948b65bda5bda8dd50986fa4cbd231/LoRa_E22.cpp#L640

**Comment by xreef** [comment]
Hi Matteo,
yes It's a bug, I'm going to fix it as soon as possible.
Bye Renzo

**Comment by xreef** [comment]
Hi @MatteoGalet,
I verified, and seems It's all ok; before launch the message to the module, I set the specified save type

https://github.com/xreef/EByte_LoRa_E22_Series_Library/blob/510e04e617948b65bda5bda8dd50986fa4cbd231/LoRa_E22.cpp#L617

but after I receive the response from the ebyte and the command is overwritten from the command response,

https://github.com/xreef/EByte_LoRa_E22_Series_Library/blob/510e04e617948b65bda5bda8dd50986fa4cbd231/LoRa_E22.cpp#L627

then I do a compare with RETURNED_COMMAND that is C1 every time.

https://github.com/xreef/EByte_LoRa_E22_Series_Library/blob/510e04e617948b65bda5bda8dd50986fa4cbd231/LoRa_E22.cpp#L640

Bye Renzo
