### ISSUE TITLE
FREQUENCY_915 is incorrect

### ISSUE THREAD

**Issue by berk-ott** [xreef/EByte_LoRa_E22_Series_Library#16]
Thank you in advance!

'OPERATING_FREQUENCY' is set to 850 
I set it to 902 in my copy of statesNaming.h
But I am not sure if that is correct.
Is it supposed to be bottom of the band?

#elif defined(FREQUENCY_868)
	#define OPERATING_FREQUENCY 850
#elif defined(FREQUENCY_915)
>>>>>	// This is incorrect?  #define OPERATING_FREQUENCY 850. <<<<<
	#define OPERATING_FREQUENCY 902 // LORA_HBO 2022-12-27
#else
	#define OPERATING_FREQUENCY 410
#endif

setConfiguration reports
Chan : 0 -> 902MHz

https://www.baranidesign.com/faq-articles/2019/4/23/lorawan-usa-frequencies-channels-and-sub-bands-for-iot-devices

**Comment by berk-ott** [comment]
#elif defined(FREQUENCY_915)
	// This is incorrect?  #define OPERATING_FREQUENCY 850
	#define OPERATING_FREQUENCY 902 // LORA_HBO 2022-12-27

I actually set it to 902

setConfiguration reports
Chan : 0 -> 902MHz

**Comment by xreef** [comment]
Hi Berk,
the LoRa 915Mhz device no more exists, now is substituted with 868Mhz that cove also 900Mhz frequencies.
bye Renzo
