### ISSUE TITLE
How to add key for e22 lora modules

### ISSUE THREAD

**Issue by fixajteknik** [xreef/EByte_LoRa_E22_Series_Library#17]
Well i can cahnge all parameters with your library thanks 🙏. But i cant change the password which is key labelled as at the Rf setting software. 

![Screenshot_20230110_044234_Chrome](https://user-images.githubusercontent.com/73440569/211442691-0aa83f36-a722-4f32-bf92-b34076bbd3e3.jpg)

**Comment by xreef** [comment]
Hi,
but key I think It's the encryption key, and you can set It with 

https://github.com/xreef/EByte_LoRa_E22_Series_Library/blob/master/LoRa_E22.h#L205

configuration.CRYPT.CRYPT_H 
configuration.CRYPT.CRYPT_L 

Give me a feedback.
Bye Renzo

**Comment by fixajteknik** [comment]
thanks it works

**Comment by xreef** [comment]
Thank a lot for your tests.
Bye Renzo
