### ISSUE TITLE
Arduino Nano gets/sends incorrect data. Looks like a bug in the library - Strings or memory manipulation.

### ISSUE THREAD

**Issue by zhekaus** [xreef/EByte_LoRa_E22_Series_Library#18]
Arduino Nano gets/sends incorrect data. Looks like a bug in the library - Strings or memory manipulation.
I tried two examples:

1) Arduino_e22_05_SendFixedTransmissionStructure
2) esp8266_e22_04_SendFixedTransmission

Esp8266 sends/gets correct text:

Success
  Hello, world?”

Arduino Nano sends/gets the following wrong text:
Success
ccessorld? 

We can see part of «Success» insead of «Hello, w»

**Comment by fixajteknik** [comment]
Well i am not the author of library but i have tested all codes and i didnt see that problem. Can you share 

> your codes,
> lora parameters settings,
> lora modules model numbers,
> circut board images,
> schematic.

Sometimes if a user using white board and if there is a loose contact that will happen.
