### ISSUE TITLE
ESP32-E22  No response from device

### ISSUE THREAD

**Issue by luisgcu** [xreef/EByte_LoRa_E22_Series_Library#2]
Hello, 
First of all thank you   for your  work in this library, looks good!
I am having  E22 Connected to ESP 32  I loaded couple examples,  I have the following definition for ESP32 pins:
// ---------- esp32 pins --------------
LoRa_E22 e22ttl100(&Serial2, 15, 21, 19); //  RX AUX M0 M1
**I Always gets  "No response from device! (Check wiring)"**  
wiring is ok. 
Module  actually transmits, I am able to see when transmitting using SDR sharp. 
I just get the error at initialization. 
I also tried the example Arduino_e22_getConfiguration, and I got this:

No response from device! (Check wiring)
12
No response from device! (Check wiring)
12
----------------------------------------
Model no.: 112
Version  : 111
Features : 1101110
----------------------------------------

 these are my connections with ESP32
* E22      ----- esp32
 * M0         ----- 21 
 * M1         ----- 19 
 * RX         ----- TX2 (PullUP, 4.7k)
 * TX         ----- RX2 (PullUP, 4.7k )
 * AUX        ----- 15  (PullUP 4.7k)
 * VCC        ----- 3.3v
 * GND        ----- GND
 *

**Comment by xreef** [comment]
Hi Luisgcu,
if the connection was ok and the device works correctly I don't see any problem.
Try to put 5v on VCC.
Bye Renzo
