### ISSUE TITLE
Support E32868T30D based on SEMTECH's SX1276 RF

### ISSUE THREAD

**Issue by molavy2003** [xreef/EByte_LoRa_E22_Series_Library#21]
Hi there
i try setup E32868T30D Lora Module using this library with no success 
is there any guide about how i can setup and get it work?
when i setup wiring and run arduinoGetConfiguration
i get now response from module check wiring 
best regards

**Comment by xreef** [comment]
Hi,
you can find the complete [guide here](https://www.mischianti.org/category/my-libraries/ebyte-lora-e22-devices/).
Bye Renzo
