### ISSUE TITLE
configuration.getChannelDescription() reports wrong E22 frequency

### ISSUE THREAD

**Issue by sidtupper** [xreef/EByte_LoRa_E22_Series_Library#26]
I'm using some E22-900T30D modules.  When I run your example at 

https://github.com/xreef/EByte_LoRa_E22_Series_Library/tree/master/examples/esp32_e22_setConfiguration)
/esp32_e22_setConfiguration.ino

it returns  Chan : 23 -> 433MHz, when I expect it to return 850 + 23  -> 873MHz.

Does this matter?  In other words, is it just informational, or does it result in wrong commands to the module?

A related problem is it returns an error "POWER_30 was not declared" when attempting to set the configuration to POWER_30.   I can't find "#define E22_22" or "#define E22_30" in the repository so I guess TRANSMISSION_POWER gets enumerated as though for E22-400 in line 467 of statesNaming.h.  Adding "#define FREQUENCY_915" and "#define E22_30" in the example code seems to fix it.

**Comment by xreef** [comment]
Hi Sid,
Ahh, I checked that you wrote "Adding "#define FREQUENCY_915" and "#define E22_30" in the example code seems to fix it.".
So I think it's all okay now.
Some additional info [here](https://mischianti.org/forums/topic/esp8266-wemos-d1-mini-and-e220-900t30d-frequencies-problem-and-info/).
Bye Renzo
