### ISSUE TITLE
How to add sender and receiver addresses? Using ESP32

### ISSUE THREAD

**Issue by JayZeeM** [xreef/EByte_LoRa_E22_Series_Library#27]

**Comment by JayZeeM** [comment]
This is for a communication device that connects each other without LoRaWAN or internet.

**Comment by xreef** [comment]
Hi jay,
You can add the sender address in the payload, the receiver it's already present in the device.
Bye Renzo

**Comment by JayZeeM** [comment]
I mean like where will I input the receiver's address in the sending end? Can you provide and example?

**Comment by JayZeeM** [comment]
Do you also have a project of connecting an ESP32 to a phone passing data through an application

**Comment by JayZeeM** [comment]
Do you also have a project of connecting an ESP32 to a phone passing data through an application

**Comment by xreef** [comment]
Hi Jay,
To add the address, you need to manage the structure you send and put it inside a managed position.
To communicate your ESP32 with cellular, you can use Bluetooth, which can work like a wireless UART.
But I don't have any examples.
Bye Renzo
