### ISSUE TITLE
how to acces KEY parameters of E22 dynamically on code

### ISSUE THREAD

**Issue by fixajteknik** [xreef/EByte_LoRa_E22_Series_Library#30]
![key](https://github.com/user-attachments/assets/d0456d7a-b527-4790-8b86-bcf7aa4afb7a)

well there is a parameter setting "KEY" on RF setting app write only. and also there is a part of code on your library. But how I can use I didnt see any example code on your docs
 
```
struct Crypt {
	byte CRYPT_H = 0;
	byte CRYPT_L = 0;
};
```

also register is exactly to showing key 

![image](https://github.com/user-attachments/assets/dadcd46b-1038-41f2-90f1-508619a53a6c)

**Comment by xreef** [comment]
Hi Fixaj,
you can find information about that [here](https://mischianti.org/forums/topic/lora-e220-and-sending-data-with-security/).
Bye Renzo
