### ISSUE TITLE
questions about E22-900M22S

### ISSUE THREAD

**Issue by arifainchtein** [xreef/EByte_LoRa_E22_Series_Library#9]
Hello,
I am looking into the E22-900M22S chip.  Can i use it with your library?
Also, in your examples you use the E22-900T22S U chip which has the pins M0, M1 and AUX but the E22-900M22S has DI01 and DIO2 and BUSY.  Can i assume that DIO1 is M0, DIO2 is M1 and BUSY is AUX?

thanks

**Comment by arifainchtein** [comment]
Also, I have been looking but i cant seem to find what are M0 and M1 and AUX are used for.  Could you tell me what are they used for?
thanks

**Comment by xreef** [comment]
Hi, ari,
I answer your questions [here](https://www.mischianti.org/forums/topic/e22-900m22s-wiring-dio1-dio2-and-busy).
Bye Renzo
